### ISSUE TITLE
Icon request: T-Picker Icon 

### ISSUE THREAD

**Issue by Utkarsh1504** [Binary-Cumates/T-Picker-Frontend#19]
## About T-Picker Icon
design a new icon with an extension .ico .svg .png.

**make a PR and link this issue** 
e.g.  Issue #`<IssueNo>`

**Also, attach a preview of the icon with your PR**

**Comment by iamdevvalecha** [comment]
why? new issue

**Comment by Utkarsh1504** [comment]
@iamdevvalecha  I think in the future we will need a logo and png for our frontend part that's why i raised this issue so that we have our official logo

**Comment by iamdevvalecha** [comment]
@Utkarsh1504 we already have.
