### ISSUE TITLE
setup: codecov report for pull request.

### ISSUE THREAD

**Issue by iamdevvalecha** [Binary-Cumates/T-Picker-Frontend#23]
helps to genrate covrage report.
https://github.com/apps/codecov

**Comment by iamdevvalecha** [comment]
not fixed yet.

**Comment by Utkarsh1504** [comment]
here you can see it is in the action of workflow
![Screenshot (37)](https://user-images.githubusercontent.com/76392681/123508468-4cabea80-d68d-11eb-8844-39d029566b4c.png)

**Comment by Utkarsh1504** [comment]
maybe you also have to make an account on codecov then enable it maybe then it works

**Comment by iamdevvalecha** [comment]
wiat

**Comment by iamdevvalecha** [comment]
![Screenshot from 2021-06-26 14-59-48](https://user-images.githubusercontent.com/71969867/123508885-b62cf880-d68f-11eb-9e81-207da8f498a5.png)

**Comment by iamdevvalecha** [comment]
we want codecov report like this...

**Comment by Utkarsh1504** [comment]
ok
